# Generated by Django 4.2.2 on 2025-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_persons",
                    models.PositiveIntegerField(verbose_name="Количество персон"),
                ),
                (
                    "date_time_of_reservation",
                    models.DateTimeField(verbose_name="Дата и время бронирования"),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(max_length=2, verbose_name="Номер стола"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("reserved", "Забронирован"), ("free", "Свободен")],
                        default="free",
                        max_length=15,
                        verbose_name="Статус бронирования стола",
                    ),
                ),
                (
                    "number_of_seats",
                    models.PositiveIntegerField(
                        verbose_name="Количество мест за столом"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
            },
        ),
    ]
