# Generated by Django 4.2.2 on 2025-07-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="description",
            field=models.TextField(
                blank=True, max_length=300, null=True, verbose_name="Описание стола"
            ),
        ),
    ]
