# Generated by Django 4.2.2 on 2025-07-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_table_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_number",
            field=models.IntegerField(unique=True, verbose_name="Номер стола"),
        ),
    ]
