# Generated by Django 4.2.2 on 2025-07-19 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_table_table_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="date_time_of_reservation",
        ),
        migrations.AddField(
            model_name="reservation",
            name="date_of_reservation",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата бронирования"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="time_of_reservation",
            field=models.TimeField(
                default=datetime.time(11, 0), verbose_name="Время бронирования"
            ),
        ),
    ]
