# Generated by Django 4.2.2 on 2025-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_remove_reservation_date_time_of_reservation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="status",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("table", "date_of_reservation", "time_of_reservation"),
                name="unique_reservation",
            ),
        ),
    ]
